# Coolify-optimized Docker Compose configuration
# This fixes volume conflicts and removes unnecessary services

services:
  app:
    container_name: docling-api
    build:
      context: .
      args:
        CPU_ONLY: "true"
    image: docling-api:latest
    command: poetry run uvicorn --port 8080 --host 0.0.0.0 main:app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - ENV=production
      - MALLOC_ARENA_MAX=2
      - OMP_NUM_THREADS=2
      - PYTHONMALLOC=malloc
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      args:
        CPU_ONLY: "true"
    image: docling-api:latest
    command: poetry run celery -A worker.celery_config worker --pool=solo -n worker_primary --loglevel=info
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - ENV=production
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
