# Single-service version for Coolify
# This runs everything in one container for simplicity

services:
  app:
    container_name: docling-api
    build:
      context: .
      args:
        CPU_ONLY: "true"
    image: docling-api:latest
    command: |
      sh -c "
        redis-server --daemonize yes &&
        poetry run celery -A worker.celery_config worker --pool=solo -n worker_primary --loglevel=info &
        poetry run uvicorn --port 8080 --host 0.0.0.0 main:app
      "
    environment:
      - REDIS_HOST=redis://localhost:6379/0
      - ENV=production
      - MALLOC_ARENA_MAX=2
      - OMP_NUM_THREADS=2
      - PYTHONMALLOC=malloc
    ports:
      - "8080:8080"
    volumes:
      - model_cache:/tmp
    restart: unless-stopped

volumes:
  model_cache:
